### ISSUE TITLE
Practica de Calidad

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-calidad-entrevista-tr#1]
[Práctica de Calidad.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calidad-entrevista-tr/files/7345061/Practica.de.Calidad.pdf)

**Comment by ThorSampy** [comment]
Trabajo completo y bien echo: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
